name: Deploy Shared Infrastructure

on:
  push:
    branches: [main]

jobs:
  test-self-hosted-runner:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: 'terraform --version'

    - name: 'Verify PWSH Version'
      shell: pwsh
      run: '$host'

    - name: 'Verify Access to Local Domain'
      shell: pwsh
      run: 'Get-AdDomain cglabs.work'

    - name: 'Verify AZ CLI Version'
      shell: pwsh
      run: 'az --version'

    - name: 'Verify Packer Version'
      shell: pwsh
      run: 'packer --version'