name: Deploy Shared Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploySharedServices:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login Azure Cli
      shell: pwsh
      run: 'az login --identity'

    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: 'terraform -chdir=".\infra-as-code\deployments\cglabs-avd-eus-sharedsvcs" init'