name: Deploy Shared Infrastructure

on:
  push:
    branches: [main]

jobs:
  test-terraform:
    runs-on: Default
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: 'terraform --version'

    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: '$host'

    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: 'Get-AdDomain'
