name: Deploy Shared Infrastructure

on:
  push:
    branches: [master]

jobs:
  test-terraform:
    runs-on: AzureHosted
    steps:
    - name: 'Verify Terraform Installed'
      shell: pwsh
      run: 'terraform --version'
