name: Deploy Shared Infrastructure

on:
  push:
    branches: [main]

jobs:
  deploySharedServices:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login Azure Cli
      shell: pwsh
      run: 'az login --identity'

    - name: Set AVD PoC Subscription
      shell: pwsh
      run: 'az account set --subscription "cglabs-avd-poc"'

    - name: 'Terraform Init'
      shell: pwsh
      run: 'terraform -chdir=".\infra-as-code\deployments\cglabs-avd-eus-sharedsvcs" init'

    - name: 'Terraform Plan'
      shell: pwsh
      run: 'terraform -chdir=".\infra-as-code\deployments\cglabs-avd-eus-sharedsvcs" plan -out sharedsrvs.tfplan'

    - name: Logout Azure Cli
      shell: pwsh
      run: 'az logout'